name: Lint

on: [pull_request]

jobs:
  build:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter@v4.9.1
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
